stages:
  - test
  - build
  - verify

image: viperdev/ionic:xenial

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache/"
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  ANDROID_ARTIFACT_DIR: $CI_PROJECT_DIR/platforms/android/app/build/outputs/apk

cache:
  key: node-pnpm
  paths: &node_lock_cache_paths
    - .pnpm-store

.npm_init: &npm_init |
  export PATH=$CI_PROJECT_DIR/node_modules/.bin:$CI_PROJECT_DIR/.ci/bin:$PATH
  npm set optional false
  npm set production true
  npm set dev true
  rm -rf node_modules
  npm set store $CI_PROJECT_DIR/.pnpm-store
  npm set pnpmfile $CI_PROJECT_DIR/pnpmfile.js
  npm set prefer-frozen-shrinkwrap true
  npm set prefer-offline true
  [ -n "$(which pnpm 2>/dev/null)" ] || npm install -g pnpm
  ln -s $(which pnpm) .ci/bin/npm
  ln -s $(which pnpx) .ci/bin/npx

before_script:
  - ulimit -c unlimited
  - *npm_init
  - pnpm install --no-save
  - change-environment "$CI_COMMIT_REF_NAME"

.collect_artifacts: &collect_artifacts
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - www
      - www-dev-backendless
      - $ANDROID_ARTIFACT_DIR
      - core

test:lint:
  image: viperdev/coala-ngx
  stage: test
  cache: {}
  before_script: []
  script: coala --ci --verbose --flush-cache

build:dev:web:
  <<: *collect_artifacts
  stage: build
  script:
    - change-environment backendless
    - build-www
    - mv www www-dev-backendless

build:prod:web:
  <<: *collect_artifacts
  stage: build
  script:
    - build-www --prod

verify:e2e:
  stage: verify
  image: selenium/standalone-chrome:latest
  dependencies:
    - build:dev:web
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - e2e_report
    when: always
  cache:
    key: e2e-pnpm
    paths: *node_lock_cache_paths
  variables:
    PROTRACTOR_RETRIES: 4
  before_script:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - . "$HOME/.nvm/nvm.sh"  # This loads nvm
    - nvm install 8
    - npm install -g pnpm
    - pnpm install typescript
                  eslint
                  eslint-plugin-protractor
                  http-server-spa
                  jasmine-spec-reporter
                  promise-retry
                  protractor
                  protractor-flake
                  protractor-screenshoter-plugin
                  request
                  request-promise-any
                  ts-node
                  '@types/jasmine'
                  '@types/node'
    - export PATH=$CI_PROJECT_DIR/.ci/bin:$PATH
    - pnpm run e2e-update
  script: test-e2e www-dev-backendless
