stages:
  - test
  - build
  - verify

image: jayvdb/ionic:xenial

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache/"
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  ANDROID_ARTIFACT_DIR: $CI_PROJECT_DIR/platforms/android/app/build/outputs/apk

cache:
  key: node-npm
  paths: &node_lock_cache_paths
    - node_modules
    - .npm

.npm_init: &npm_init |
  export PATH=$CI_PROJECT_DIR/.ci/bin:$PATH
  npm set optional false
  npm set production true
  npm set dev true
  npm set cache $CI_PROJECT_DIR/.npm
  npm --version
  npm --silent rebuild > /dev/null

before_script:
  - *npm_init
  - npm install --no-save
  - change-environment "$CI_COMMIT_REF_NAME"

.collect_artifacts: &collect_artifacts
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - www
      - www-dev-offline
      - $ANDROID_ARTIFACT_DIR

test:lint:
  image: okdocker/pynode:3.6-10.x
  stage: test
  cache:
    key: coala-npm
    paths:
      - .cache/pip
      - .npm
  before_script:
    - *npm_init
    - npm install -g csscomb sass-lint
  script: test_lint

test:tslint:
  stage: test
  image: node:8
  cache:
    key: tslint-npm
    paths: *node_lock_cache_paths
  script:
    - npm install --no-save
        tslint codelyzer tslint-eslint-rules
    - npx ionic-app-scripts lint --bailOnLintError true

build:dev:web:
  <<: *collect_artifacts
  stage: build
  script:
    - change-environment offline
    - build-www
    - mv www www-dev-offline

build:dev:android:
  <<: *collect_artifacts
  stage: build
  variables:
    BUILD_FLAGS: --debug
  script: &android_build
    - ionic cordova build android $BUILD_FLAGS
    - ls -al $ANDROID_ARTIFACT_DIR

build:prod:web:
  <<: *collect_artifacts
  stage: build
  script:
    - build-www --prod

build:prod:android:
  <<: *collect_artifacts
  stage: build
  variables:
    BUILD_FLAGS: --prod --release
  script: *android_build

verify:e2e:
  stage: verify
  image: selenium/standalone-chrome:latest
  dependencies:
    - build:dev:web
  cache:
    key: e2e
    paths:
      - node_modules
  before_script:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - . "$HOME/.nvm/nvm.sh"  # This loads nvm
    - nvm install 8
    - npm install -g http-server jasmine-spec-reporter minimist protractor
                     ts-node '@types/jasmine'
    - export PATH=$CI_PROJECT_DIR/.ci/bin:$PATH
    - sleep 5
  script: test-e2e www-dev-offline
