overrides: picshare-ionic.yaml

project_name: picshare
name: picshare-ionic
theme: picshare-theme

# Remove lock_moban to customise this file
lock_moban: true

configuration:
  configuration: .moban.yaml
  template_dir:
    - ../ionic-template/templates/
    - ../ionic-template/
  configuration_dir: ../ionic-template/
targets:
  - .moban.yaml: moban.yaml.jj2
  - README.md: README.md.jj2
  - .gitlab-ci.yml: gitlab-ci.yml.jj2
  - netlify.toml: netlify.toml.jj2
  - tsconfig.json: tsconfig.json.jj2
  - package.json: package.json.jj2
  - src/app/main.ts: app/main.ts.jj2
  - src/global.ts: global.ts.jj2
  - src/index.html: index.html.jj2
  - src/app/app.module.ts: app/module.ts.jj2
  - src/app/app.component.ts: app/component.ts.jj2
  - src/app/constants.ts: app/constants.ts.jj2
  - src/models/.gitignore: app/gitignore.jj2
  - src/pages/.gitignore: app/gitignore.jj2
  - src/providers/.gitignore: app/gitignore.jj2
  - config.xml: config.xml.jj2
  - config/copy.config.js: config/copy.config.js.jj2
  - ionic.config.json: ionic.config.json.jj2
  - src/theme/colors.scss: colors.scss.jj2
  - src/theme/site_variables.scss: theme_variables.scss.jj2
  - src/theme/variables.scss: variables.scss.jj2
  - src/assets/i18n/en.json: i18n/en.json.jj2
  - src/assets/i18n/de.json: i18n/de.json.jj2
copy:
  - src/config/environment.ts: environments/local.ts
  - .gitignore: .gitignore
  - pnpmfile.js: pnpmfile.js
  - .coafile: .coafile
  - .sass-lint.yml: .sass-lint.yml
  - .editorconfig: .editorconfig
  - tslint.json: tslint.json
  - .ci/bin/: .ci/bin/
  - environments/: environments/**
  - src/models/: src/models/**
  - ionic.starter.json: ionic.starter.json
  - resources/: resources/**
  - resources/android/: resources/android/**
  - resources/ios/: resources/ios/**
  - README.md: README.md
  - src/manifest.json: src/manifest.json
  - src/app/authHttpServiceFactory.ts: src/app/authHttpServiceFactory.ts
  - src/app/app.html: src/app/app.html
  - src/app/app.scss: src/app/app.scss
  - src/app/backends/: src/app/backends/
  - src/components/: src/components/**
  - src/config/environment.ts: src/config/environment.ts
  - src/pages/eventfront/: src/pages/eventfront/
  - src/pages/about/: src/pages/about/
  - src/pages/home/: src/pages/home/
  - src/pages/settings/: src/pages/settings/
  - src/pages/login/: src/pages/login/
  - src/pages/signup/: src/pages/signup/
  - src/pages/logout/: src/pages/logout/
  - src/pages/welcome/: src/pages/welcome/
  - src/pages/passwordreset/: src/pages/passwordreset/
  - src/pages/passwordresetconfirm/: src/pages/passwordresetconfirm/
  - src/pages/profile/: src/pages/profile/
  - src/pages/tandc/: src/pages/tandc/
  - src/pages/not-found/: src/pages/not-found/
  - src/pages/product/: src/pages/product/
  - src/pages/event/: src/pages/event/
  - src/pages/eventlist/: src/pages/eventlist/
  - src/pages/eventcreate/: src/pages/eventcreate/
  - src/pages/payment/: src/pages/payment/
  - src/pages/cookieconsent/: src/pages/cookieconsent/
  - src/pages/debug/: src/pages/debug/
  - src/pipes/: src/pipes/**
  - src/providers/: src/providers/**
  - src/decorators/: src/decorators/**
  - src/theme/picshare-theme.scss: src/theme/picshare-theme.scss
  - tests/e2e/: tests/e2e/**
  - jasmine.json: jasmine.json
