rules:
  attribute-quotes: 0
  leading-zero: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-css-comments: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-empty-rulesets: 0
  no-ids: 0
  no-important: 0
  no-qualifying-elements: 0
  no-trailing-zero: 0
  no-vendor-prefixes: 0
  single-line-per-selector: 0
  space-after-comma: 0
  indentation:
    - 2
    -
      size: 2
  # used only in trackbnb
  class-name-format: 0
  no-url-domains: 0
  no-url-protocols: 0
