[settings]
  id = '2a1bf4fd-d168-41c7-bfca-57fc63cfcb0b'

[build]
  command = 'export PATH=./.ci/bin/:"$PATH" && build-netlify'
  publish = 'www'

[[redirects]]
  from = '/api/*'
  to = 'https://api.picllary.de/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[plugins.local.server]
  static = true
  lambda = false
  port = 8100
