export const services = [
    {
        title: 'Ich mähe ihren Rasen',
        description: 'ich kann auch noch dies und das. zum beispiel Bäume fällen und Gartenteiche buddeln',
        category: 'garden',
        price: 12,
        currency: 'EUR',
        star: false,
        location: {
            lat: 53.464218,
            lng: 9.983108,
        },
        profile: {
            name: 'Emil Höfling',
            city: 'Hamburg',
            country: 'Germany',
            img: 'Path/to/file.img',
            mail: 'emil.hoefling@viperdev.io',
        },
    },
    {
        title: 'Ich arbeite als Elektriker.',
        description: 'Ich sorge unter Ander\'m für den Fluss der Energie. Mit meiner starken Leistung lad\' ich eure Batterie.',
        category: 'electrics',
        price: 15,
        currency: 'EUR',
        star: true,
        location: {
            lat: 53.488166,
            lng: 9.9968333,
        },
        profile: {
            name: 'Emil Höfling',
            city: 'Hamburg',
            country: 'Germany',
            img: 'Path/to/file.img',
            mail: 'emil.hoefling@viperdev.io',
        },
    },
    {
        title: 'Ich mach alles neu',
        description: 'Ich kaufe mir Baumaschinen, Bagger und Walzen und Kräne\nStürze mich auf Berlin, drück auf die Sirene',
        category: 'construction',
        price: 15,
        currency: 'EUR',
        star: true,
        location: {
            lat: 53.460249,
            lng: 9.9752563,
        },
        profile: {
            name: 'Emil Höfling',
            city: 'Hamburg',
            country: 'Germany',
            img: 'Path/to/file.img',
            mail: 'emil.hoefling@viperdev.io',
        },
    },
    {
        title: 'Ich mache Buchhaltung',
        description: 'ich mache Buchhaltung, also werden alle Steuern pünktlich bezahlt',
        category: 'bookkeeping',
        price: 20,
        currency: 'EUR',
        star: false,
        location: {
            lat: 53.464208,
            lng: 9.993108,
        },
        profile: {
            name: 'Emil Höfling',
            city: 'Hamburg',
            country: 'Germany',
            img: 'Path/to/file.img',
            mail: 'emil.hoefling@viperdev.io',
        },
    },
    {
        title: 'Ich mache Reparaturen',
        description: 'Ich repariere alte Möbel',
        category: 'repairs',
        price: 10,
        currency: 'EUR',
        star: false,
        location: {
            lat: 53.454218,
            lng: 9.983108,
        },
        profile: {
            name: 'Emil Höfling',
            city: 'Hamburg',
            country: 'Germany',
            img: 'Path/to/file.img',
            mail: 'emil.hoefling@viperdev.io',
        },
    },
];
