export const services = [
    {
        id: 1,
        user: {
            id: 1,
            email: 'emil.hoefling@viperdev.io',
            bio: null,
            first_name: 'Emil',
            last_name: 'Höfling',
            city: 'Hamburg',
            country: 'Germany',
            image: 'Path/to/file.img',
        },
        name: 'Ich mähe ihren Rasen',
        description: 'ich kann auch noch dies und das. zum beispiel Bäume fällen und Gartenteiche buddeln',
        price: '12',
        currency: 'EUR',
        latitude: '53.464218',
        longitude: '9.983108',
        category: {
            name: 'garden',
            icon: 'nutrition',
            img_url: 'https://images.unsplash.com/photo-1470259478948-d5605cd2fe53?w=300&q=80',
        },
        recommended: 'False',
    },
    {
        id: 2,
        user: {
            id: 1,
            email: 'emil.hoefling@viperdev.io',
            bio: '',
            first_name: 'Emil',
            last_name: 'Höfling',
            city: 'Hamburg',
            country: 'Germany',
            image: 'Path/to/file.img',
        },
        name: 'Ich arbeite als Elektriker.',
        description: 'Ich sorge unter Ander\'m für den Fluss der Energie. Mit meiner starken Leistung lad\' ich eure Batterie.',
        price: '15',
        currency: 'EUR',
        star: true,
        latitude: '53.488166',
        longitude: '9.9968333',
        category: {
            name: 'electrics',
            icon: 'bulb',
            img_url: 'https://images.unsplash.com/photo-1518081461904-9d8f136351c2?w=300&q=80',
        },
        recommended: 'False',
    },
    {
        id: 3,
        user: {
            id: 1,
            email: 'emil.hoefling@viperdev.io',
            bio: '',
            image: 'Path/to/file.img',
            first_name: 'Emil',
            last_name: 'Höfling',
            city: 'Hamburg',
            country: 'Germany',
        },
        name: 'Ich mach alles neu',
        description: 'Ich kaufe mir Baumaschinen, Bagger und Walzen und Kräne\nStürze mich auf Berlin, drück auf die Sirene',
        price: '15',
        currency: 'EUR',
        star: true,
        latitude: '53.460249',
        longitude: '9.9752563',
        category: {
            name: 'construction',
            icon: 'construct',
            img_url: 'https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?w=300&q=80',
        },
        recommended: 'False',
    },
    {
        id: 4,
        user: {
            id: '1',
            email: 'emil.hoefling@viperdev.io',
            bio: '',
            image: 'Path/to/file.img',
            first_name: 'Emil',
            last_name: 'Höfling',
            city: 'Hamburg',
            country: 'Germany',
        },
        name: 'Ich mache Buchhaltung',
        description: 'ich mache Buchhaltung, also werden alle Steuern pünktlich bezahlt',
        price: '20',
        currency: 'EUR',
        star: false,
        latitude: '53.464208',
        longitude: '9.993108',
        category: {
            name: 'bookkeeping',
            icon: 'cash',
            img_url: 'https://images.unsplash.com/photo-1521540216272-a50305cd4421?w=300&q=80',
        },
        recommended: 'False',
    },
    {
        id: 5,
        user: {
            id: '1',
            email: 'emil.hoefling@viperdev.io',
            bio: '',
            image: 'Path/to/file.img',
            first_name: 'Emil',
            last_name: 'Höfling',
            city: 'Hamburg',
            country: 'Germany',
        },
        name: 'Ich mache Reparaturen',
        description: 'Ich repariere alte Möbel',
        price: '10',
        currency: 'EUR',
        star: false,
        latitude: '53.454218',
        longitude: '9.983108',
        category: {
            name: 'repairs',
            icon: 'hammer',
            img_url: 'https://images.unsplash.com/photo-1534398079543-7ae6d016b86a?w=300&q=80',
        },
        recommended: 'False',
    },
];
