import { Days, Pickup, Status } from '../../models/pickups';

export const pickups: Pickup[] = [
  { id: 1,
    name: 'My Tuesday Pickup',
    business: 'Viper Development UG (haftungsbeschränkt)',
    address_line_1: 'Harburger Schlossstrasse 6-12',
    address_line_2: '21079 Hamburg, Germany',
    suburb: 'Hamburg',
    city: 'Hamburg',
    postal_code: 'HRB 147102',
    lat: 12.3456,
    long: 45.678,
    recurring: true,
    day_of_week: Days.Tuesday,
    weight: 32.0,
    user_id: 3,
    termination_date: new Date(new Date().getTime() + 7 * 24 * 3600),
    status: Status.Active,
  },
  { id: 2,
    name: 'My Pickup',
    business: 'Viper Development UG (haftungsbeschränkt)',
    address_line_1: 'Harburger Schlossstrasse 6-12',
    address_line_2: '21079 Hamburg, Germany',
    suburb: 'Hamburg',
    city: 'Hamburg',
    postal_code: 'HRB 147102',
    lat: 98.765,
    long: 54.321,
    recurring: false,
    weight: 31.0,
    user_id: 3,
    termination_date: new Date('January 1, 2018 00:00:00'),
    status: Status.Inactive,
  },
  { id: 3,
    name: 'My 3rd Pickup',
    business: 'Viper Development UG (haftungsbeschränkt)',
    address_line_1: 'Harburger Schlossstrasse 6-12',
    address_line_2: '21079 Hamburg, Germany',
    suburb: 'Hamburg',
    city: 'Hamburg',
    postal_code: 'HRB 147102',
    lat: 87.654,
    long: 321.456,
    recurring: false,
    weight: 30.0,
    user_id: 3,
    termination_date: new Date('January 1, 2017 00:00:00'),
    status: Status.Inactive,
  },
];
